language: node_js
node_js:
  - "4"
branches:
  only:
    - master
before_script:
  - npm install coveralls html-webpack-plugin webpack ecstatic
  - webpack --config webpack.test.js
script:
  - ./run-tests.sh
sudo: false
